### ISSUE TITLE
Startup app setup

### ISSUE THREAD

**Issue by mthais** [mthais/resumeweb#1]
### How this app work

Resumeweb is an application that allows create a web curriculum with a different and attractive look for companies.
The professional will enter your information in the application and you can get HR consulting from people who specialize in this area, this coach will help the professional find the best way to stand out in the job market. The system will allow the user to choose a creative layout for their resume.

### Description

* To Start this project is necessary the configuration of app like as:
* Install node.js and react
* Install database
* Integrate Heroku with github

### Requirements to complete this issue

- You should start, in a Github repo, a basic setup with Node.js and React, in the latests versions, and install the dependencies and a basic server, and run a simple server with express on the node side, and react on the front-end, running locally in your machine. 
- It should be possible see a Hello World React app
- Docker is a plus. Create a self container configuration

### References
You can use the same setup as [Gitpay](https://github.com/worknenjoy/gitpay)

It should be possible in the end follow the steps on the documentation about how to run the project:
[See documentation](https://github.com/mthais/resumeweb)

**Comment by mthais** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Install node.js and react](https://trello.com/c/XrlTSabR/5-install-nodejs-and-react)

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/65

**Comment by mthais** [comment]
@villasboas Good job. Thanks a lot.
