### ISSUE TITLE
Configure eslint on project

### ISSUE THREAD

**Issue by mthais** [mthais/resumeweb#14]
It's necessary to configure the eslint with auto fix option on this project.

### Why
We need to have a code pattern on this project.

### Level
Medium

### Current behavior

When someone implements some code and gives a PR on this repository, we do not have a code pattern, so,  we have many codes without a pattern.

### Expected behavior

Configure "eslint" with auto fix resource to solve automatically the pattern of code.

### Screenshot attached
some screenshot

### How to solve this issue

 * Do a fork of this project;
 * Run the project locally;
 * Implement a configuration "eslint" with auto fix option and configure with the Codacy tool;
 * Do a PR in this repository starting of the fork that you did anteriorly with all solution implemented by you;

### How to play the user scenario

 - steps to reproduce the issue

### What you will need to complete this issue
Extra requirements to complete the task

### Tips
Please, verify the Gitpay repository, because we have this solution implemented there. [Gitpay repository](https://github.com/worknenjoy/gitpay).

**Comment by matvaleriano** [comment]
solved on #19

**Comment by mthais** [comment]
Issue successfully completed!
