### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by mthais** [mthais/resumeweb#17]
### Description

The goal of this issue is to create a dashboard page to the user, the Dashboard Page will have the following options:
- Links to others page on the top of the page;
- Two buttons on the top of the page, the first is "Planos"(To direct the user to Plan page) and the second is "Perfil "(This button have the following option: Conta, Contato, FAQ and Sair);
- A Card that will show news about the platform;
- A Button that allows the user create a new resume;
- Some options for the user to manage their resume are these buttons: Download, Editar,
Duplicar, Renomear, Enviar por Email, Download TXT e Deletar);

### Why

The users need to have a space to see their resume that was created and manage it.

### Level

Medium

### Current behavior

The user doesn't have one space to see the resume that he created.

### Expected behavior

When the user creates a resume, the system should show their resume on a dashboard page so that the user could manage it.

#### Dashboard Page

![screencapture-127-0-0-1-32767-start-html-2018-12-06-12_55_58](https://user-images.githubusercontent.com/27444220/49591792-952c1d00-f956-11e8-9b8e-ab73d700fdcf.png)

### How to solve this issue

* Define the logged-in route to direct the user for Dashboard Page;
* Create the frontend following the layout above to prepare all frontend to receive the backend that will be necessary;
* You don't need to think about the resume as a whole, you just need to create a component to receive the image in the future;

### How to reproduce the user scenario

 - Run the project locally;
 - Access the login page;
 - Insert your email and password;
 - Click on the button "Entrar";
 - The system should authenticate the user and redirect you to the Dashboard Page;

### What you will need to complete this issue

N/A

### Tips

- Please, use the Reactstrap existent elements;
- You will find the icons to use in this task on the following website: https://fontawesome.com/icons?d=gallery

**Comment by Github-AsraGhouri** [comment]
i have done this task

**Comment by mthais** [comment]
solved #18
