### ISSUE TITLE
Create Login/Register page

### ISSUE THREAD

**Issue by mthais** [mthais/resumeweb#3]
### Description 

To continue the project, I how PO need that you create a user login and a user register with basic data(email and password) with options (linkedin).
This funcionality will allow the user to have access on the application in the future.
For better performance these fields should have some validations such as:
The field "Nome" should have 20 characteres;
The field "Email" should have all validations about email;
The field "Senha" should have some validations such as 1  special character, 1 capital letter, 2 numbers and 4 lower case;
The field checkbox " Para Cadastrar..." is requiered;

### Why
To control all users access on application.

### Level
Medium

### Screenshot attached

**This is a user login page prototype:**

![pageshot of entrar 2018-10-08-2151 46](https://user-images.githubusercontent.com/27444220/46670050-7a803680-cba7-11e8-96f6-22869c86e3b0.png)

**This is a user register page prototype:**

![pageshot of cadastrar 2018-10-08-2152 14](https://user-images.githubusercontent.com/27444220/46670057-810eae00-cba7-11e8-9885-f004081c31c8.png)

### How to reproduze the user scenario

 **Step 1:**
    - Open the landing page;
    - Click on the button "Cadastrar" at landing page;
    - The system will show the register page;

 **Step 2:**
    - Open the landing page;
    - Click on the button "Entrar" at landing page;
    - The system will show the login page;

**Comment by alexanmtz** [comment]
@mthais , this is the screenshot

![pageshot of resume web 2018-10-23-0027 36](https://user-images.githubusercontent.com/88840/47323418-042a0c80-d65c-11e8-814a-f9297f50da4d.png)

**Comment by mthais** [comment]
Issue finalizada com sucesso!
