### ISSUE TITLE
Create Database for users 

### ISSUE THREAD

**Issue by mthais** [mthais/resumeweb#7]
### Description 
We have a frontend with 2 functionalities,  the login/register pages. They contain the following fields:
#### Login page
"Email" this field has an email validation;
"Senha" this field has a cryptography;
#### Register page
"Nome" this field is limited to 20 characters;
"Email" this field has an email validation;
"Senha" this field has a cryptography;
"Para Cadastrar..." checkbox is required;
It's necessary to create a database structure to receive the information that is inserted by users in these fields.

#### Login Page
![pageshot of entrar 2018-10-08-2151 46](https://user-images.githubusercontent.com/27444220/47470616-e801a900-d7dc-11e8-87a4-35db5ea005b3.png)
#### Register Page
![pageshot of cadastrar 2018-10-08-2152 14](https://user-images.githubusercontent.com/27444220/47470626-f6e85b80-d7dc-11e8-8c96-0800fa1e7616.png)

### Why
We need to start by creating a database structure to receive all the system. To start this structure, user's data is required.

### Level
Medium

### Current behavior
First insert the data on the form, then click on the button "Cadastrar"/ "Entrar". The system won't store the information because there isn't any database.

### Expected behavior
When the users insert their data, the system will store the data and allow the users to login on the basic page.

### How to solve this issue
* Create all structure to database by using Postgre technology to manipulating the users data. 
 This functionality should work with local and settings to heroku in production. 
 This URL of production will be made with an environment variable.

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/103

**Comment by alexanmtz** [comment]
#10
